### ISSUE TITLE
How to use midleware

### ISSUE THREAD

**Issue by cayasso** [1602/railway-routes#1]
Is there an example on how to use a middleware, for example if I want to load a user before executing a controller action, or if I want to add authentication to an action?

Thanks and great job!!

JB

**Comment by 1602** [comment]
Done. Check out example app.

**Comment by cayasso** [comment]
This is great stuff, thank you, will let you know if I see any issues.
JB

**Comment by cayasso** [comment]
Hey what about multiple middlewares, like I want one to execute first and then the other one, your example show middleware for just one resource route or namespace, what about if I want have authentication for a posts and then after user authenticate then do a loadUser, user my be used for other actions in other controllers without the need to be authenticated first so for example. In regular express:

<pre>
get('/post', authenticate, loadUser, function(req, res){}) // multiple mws
get('/comment', loadUser, function(req, res){}) // one mw
</pre>

**Comment by tj** [comment]
express also allows arrays:

get('/post', [authenticate, loadUser], fn)

etc, in fact any number of nested arrays is fine, so that should already work with this module even if not explicitly supported

**Comment by cayasso** [comment]
Awesome TJ, I didn't know that!!! is that supported in express 2.5+
Thanks!

**Comment by tj** [comment]
yup! [foo, bar, baz], [foo, [bar, baz]], [foo, [bar, [baz]] etc, it's all just flattened

**Comment by cayasso** [comment]
Wow wow!!, you see thats why I love express even for things I don't even know :) 
Thanks TJ!

**Comment by 1602** [comment]
@cayasso of course you can use this awesome feature within router helpers, just pass function or array of functions to any {middleware: ...} param. It also possible to have nested namespaces with middlewares stack.
