### ISSUE TITLE
Wrong position for route middlewares 

### ISSUE THREAD

**Issue by Unitech** [1602/railway-routes#15]
http://compoundjs.com/docs/#routing-middleware
Wrong position for the middleware.

Expected :

``` javascript
map.get('/test', middle, 'home#test');
```

But it doesn't work.

Instead this work :

``` javascript
map.get('/test', 'home#test', middle);
```

**Comment by Unitech** [comment]
I think it's okay now. How do we run the test ? Can't figure it

**Comment by 1602** [comment]
npm test
