### ISSUE TITLE
path_to for routes with optional parameters doesn't work

### ISSUE THREAD

**Issue by Unitech** [1602/railway-routes#16]
By defining

``` javascript
map.get('/test/:p1?', 'home#test');
```

When I use path_to

``` javascript
map.pathTo.test()
// I get ''
map.pathTo.test('param1')
// I get '/test/param1?'
```

---

A cool feature would be to declare route parameters like that :

``` javascript
map.get('/test/:p1/:p2?', 'home#test');
```

And to map them like that :

``` javascript
map.pathTo.test({p1 : 'param1', p2 : 'param2'})
```

Anyway thanks for this very nice piece of code

**Comment by 1602** [comment]
Thanks for spotting issue and nice api suggestion. Everything available in updated npm package (v0.0.8-4)
