### ISSUE TITLE
Issue with invalid controller actions

### ISSUE THREAD

**Issue by cayasso** [1602/railway-routes#2]
Hey @1602 I noticed an issue wen routing invalid actions

If I do <code>http://localhost:300/accounts</code> the action of the accounts controller defaults to index, if I do <code>http://localhost:300/accounts/index</code> this also default to index but if I do <code>http://localhost/accounts/invalid-action</code> I get defaulted to the show action(which I think is weird) instead of getting the "Handler not found" error message, is this intentional or it is a bug?.

Any ideas?

Thank you!

JB

This is my test handler.

<pre>
module.exports = function (app) {
    var map = new routing.Map(app, handler);    
    map.resources('accounts');  
};

function handler(ns, controller, action) {
    try {
        var ctlFile = './controllers/' + ns + controller + '_controller';
        var responseHandler =  {
            index: function (req, res) {
                res.send('IN INDEX');
            },

            show: function (req, res) {
                res.send('IN SHOW');
            },

            new: function (req, res) {
                res.send('IN NEW');
            },

            edit: function (req, res) {
                res.sed('IN EDIT');
            }

        }[action];
    } catch(e) {}
    return responseHandler || function (req, res) {
        res.send('Handler not found for ' + ns + controller + '#' + action);
    };
}
</pre>

**Comment by 1602** [comment]
Behavior is correct because pattern for show action is matched, id=invalid-action in your case. I understand your expectations, but need to dig deeper into express routing to get solution for id constraints (only accept numeric values for example).

Will check it as soon as i get my laptop back.

Thanks!
