### ISSUE TITLE
Access resource name in handler when using custom controller names.

### ISSUE THREAD

**Issue by vjpr** [1602/railway-routes#23]
If I do something like this:

```
api.resources 'collections', (collection) ->
      collection.resources 'links', controller: 'collectionLinks'
```

I wish to access the name of the resource (that is, "links"/"link") from the collectionLinks resource.

The callback receives the controllerName and there is no way to access the name of the resource.

**Comment by olalonde** [comment]
Was introduced by this commit: https://github.com/1602/railway-routes/commit/d8c3ee320c30fcf2a82f11fe079319eb9c3b2ddd Maybe @1602 knows...
