### ISSUE TITLE
Order in `only` param matters

### ISSUE THREAD

**Issue by adrianheine** [1602/railway-routes#25]
If I call `resources` with `{only: ['index', 'show', 'new', 'create']}`, `/resource/new` is interpreted as a `show` request for id `new`.

**Comment by olalonde** [comment]
This only happens when you use `only`?

**Comment by adrianheine** [comment]
Looking at the [code](https://github.com/1602/railway-routes/blob/master/lib/railway_routes.js#L382) this seems to be the case, yes. The other options depend on the order the keys of `availableRoutes` are iterated. This order is not guaranteed to be what you might expect, but it works in most if not all JS environments I know. Since order matters so much I would suggest to use an array, though.
