### ISSUE TITLE
How to add a filter in routes like you do in express ?

### ISSUE THREAD

**Issue by ktkaushik** [1602/railway-routes#26]
In express, I can add a certain filter just to check if a User has been logged in or not by doing something like this :-

``` js
app.get('/posts', ensureLoggedIn(), posts.index);
```

How do i induce the `ensureLoggedIn()` behaviour using `railway-routes` ?

**Comment by anatoliychakkaev** [comment]
map.get('/posts', ensureLoggedIn(), posts.index);

it should work for railway routes.

**Comment by ktkaushik** [comment]
as in, 

``` js
map.get('/posts', ensureLoggedIn(), 'posts#index');
```

This should work ? Because its not really working for me. I will have to edit my `handler` in this case i think.

I tried using the `middleware` parameter like you have in your example app on [this line](https://github.com/anatoliychakkaev/railway-routes-example-app/blob/master/routes.js#L9) which works fine. But i want some filter kinda functionality which executes on every request.

**Comment by ktkaushik** [comment]
btw, i am using `railway-routes` on an express app and not with `compoundjs`

**Comment by ktkaushik** [comment]
and how do i use it with `resources` ?

``` js
map.resources('posts', ensureLoggedIn());
```

 Even in this case, it loads as the middleware and not execute `ensureLoggedIn()` on every request.

Any ideas ?

**Comment by 1602** [comment]
With resources, as per example: https://github.com/anatoliychakkaev/railway-routes-example-app/blob/master/routes.js#L9
Without resources:

```
map.get('/posts', 'controllerName#actionName', function middleware(req, res,next) { next() });
```

As described here: https://github.com/1602/railway-routes/blob/master/lib/railway_routes.js#L115

**Comment by ktkaushik** [comment]
Cool, thanks.
