### ISSUE TITLE
Rename the package?

### ISSUE THREAD

**Issue by olalonde** [1602/railway-routes#6]
Hey! I just realized this npm module is completely decoupled from RailwayJS which I think it's great. Do you plan to develop it completely independently from RailwayJS? If so, why not rename the project or make it clear in the README.md. Thanks!

**Comment by anatoliychakkaev** [comment]
Yep, it was extracted from railwayjs a while ago and could be used competely independently from railwayjs. Renaming make sense, probably. I just want to make it consistent: now routes provided by that module are rails2-like, so, 'railways' as part of package name helps to understand which kind of routing provides this package.

Of course README.md requires more love, feel free to fix it to be as clear a possible from your point of view.

**Comment by olalonde** [comment]
Ok good, I'll improve the README whenever I get time :)

**Comment by 1602** [comment]
Thanks!

On Thu, Oct 4, 2012 at 3:08 PM, Olivier Lalonde notifications@github.comwrote:

> Ok good, I'll improve the README whenever I get time :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/1602/railway-routes/issues/6#issuecomment-9137831.

## 

Thanks,
Anatoliy Chakkaev
